### ISSUE TITLE
Phase 0: Build Project Framework

### ISSUE THREAD

**Issue by ErikPlachta** [ErikPlachta/Calendari#3]
###  Notes below are subject to change, incomplete, and not a true representation of the idea. 

---

---

# Phase 0:  Build Project Framework

### 1. Repo is Setup

- [x] 1.1 GitHub Created
- [x] 1.2 Everyone has access
- [x] 1.3 Pushed framework

### 2. All project-requirement App framework is built in the App

- [x] **2.1. Model / MongoDB**
    - [x] Models Defined
    - [x] Config Setup for Local DB
- [x] **2.2. Controller / Server**
   - [x] Node Server
    - [x] GraphQL connected to models
         - [x] Schema
              - [x] index.js
              - [x] resolvers.js
              - [x] typedefs.js
    - [x] Config > connection.js
    - [x] Utils
         - [x] auth.js
    - [x] GraphQL connected to models
- [x] **2.3. View / Client** 
    - [x] MVP React App 
    - [x] Utilities Onboarded
         - [x] mutations.js
         - [x] queries.js
